<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'subcategory_id' => 1,
                'code' => 'GDH010',
                'name' => 'Pivote inferior para puerta Todo Visión',
                'slug' => 'pivote-inferior-para-puerta-todo-vision',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            1 => 
            array (
                'id' => 2,
                'subcategory_id' => 1,
                'code' => 'GDH020',
                'name' => 'Pivote superior para puerta Todo Visión',
                'slug' => 'pivote-superior-para-puerta-todo-vision',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            2 => 
            array (
                'id' => 3,
                'subcategory_id' => 1,
                'code' => 'GDH030',
                'name' => 'Herraje superior vidrio vidrio puerta Todo Visión',
                'slug' => 'herraje-superior-vidrio-vidrio-puerta-todo-vision',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            3 => 
            array (
                'id' => 4,
                'subcategory_id' => 1,
                'code' => 'GDH040',
                'name' => 'Herraje superior vidrio vidrio tipo L puerta Todo Visión',
                'slug' => 'herraje-superior-vidrio-vidrio-tipo-l-puerta-todo-vision',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            4 => 
            array (
                'id' => 5,
                'subcategory_id' => 1,
                'code' => 'GDH055A',
                'name' => 'Cerradura central para puerta Todo Visión',
                'slug' => 'cerradura-central-para-puerta-todo-vision',
                'description' => 'Taca cuadrada',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            5 => 
            array (
                'id' => 6,
                'subcategory_id' => 2,
                'code' => 'GDH-D660',
                'name' => 'Kit de Pivotes superior para puerta tipo Europivot',
                'slug' => 'kit-de-pivotes-superior-para-puerta-tipo-europivot',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            6 => 
            array (
                'id' => 7,
                'subcategory_id' => 2,
                'code' => 'GDH-D663',
                'name' => 'Herraje superior para puerta tipo Europivot',
                'slug' => 'herraje-superior-para-puerta-tipo-europivot',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            7 => 
            array (
                'id' => 8,
                'subcategory_id' => 9,
                'code' => 'GDH260',
                'name' => 'Tirador circular embutido',
                'slug' => 'tirador-circular-embutido',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            8 => 
            array (
                'id' => 9,
                'subcategory_id' => 1,
                'code' => 'GDH411S',
                'name' => 'Clip de fijación doble fachada Todo Visión',
                'slug' => 'clip-de-fijacion-doble-fachada-todo-vision',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            9 => 
            array (
                'id' => 10,
                'subcategory_id' => 1,
                'code' => 'GDH416S',
                'name' => 'Clip de fijación sencillo fachada Todo Visión',
                'slug' => 'clip-de-fijacion-sencillo-fachada-todo-vision',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            10 => 
            array (
                'id' => 11,
                'subcategory_id' => 1,
                'code' => 'GDH440S',
                'name' => 'Clip de fijación cuádruple fachada Todo Visión',
                'slug' => 'clip-de-fijacion-cuadruple-fachada-todo-vision',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            11 => 
            array (
                'id' => 12,
                'subcategory_id' => 2,
                'code' => 'GDH-H600',
                'name' => 'Herramienta doble pin para Europivot',
                'slug' => 'herramienta-doble-pin-para-europivot',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            12 => 
            array (
                'id' => 13,
                'subcategory_id' => 2,
                'code' => 'GDH-D665',
                'name' => 'Pivote fijo invisible',
                'slug' => 'pivote-fijo-invisible',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            13 => 
            array (
                'id' => 14,
                'subcategory_id' => 2,
                'code' => 'GDH-D680',
                'name' => 'Tope de puerta superior vidrio-vidrio tipo Europivot',
                'slug' => 'tope-de-puerta-superior-vidrio-vidrio-tipo-europivot',
                'description' => 'Protector de goma',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            14 => 
            array (
                'id' => 15,
                'subcategory_id' => 2,
                'code' => 'GDH-D686',
                'name' => 'Soporte doble vidrio-vidrio fachada Europivot',
                'slug' => 'soporte-doble-vidrio-vidrio-fachada-europivot',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            15 => 
            array (
                'id' => 16,
                'subcategory_id' => 9,
                'code' => 'GDH260A',
                'name' => 'Tirador circular embutido',
                'slug' => 'tirador-circular-embutido',
                'description' => 'Acero inoxidable',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            16 => 
            array (
                'id' => 17,
                'subcategory_id' => 9,
                'code' => 'GDH261A',
                'name' => 'Tirador circular embutido',
                'slug' => 'tirador-circular-embutido',
                'description' => 'Grande',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            17 => 
            array (
                'id' => 18,
                'subcategory_id' => 9,
                'code' => 'GDH262A',
                'name' => 'Tirador circular embutido',
                'slug' => 'tirador-circular-embutido',
                'description' => 'Hueco',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            18 => 
            array (
                'id' => 19,
                'subcategory_id' => 3,
                'code' => 'GDH332-25',
                'name' => 'Tirador de puerta tipo C',
                'slug' => 'tirador-de-puerta-tipo-c',
                'description' => '30,5 cm de eje',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            19 => 
            array (
                'id' => 20,
                'subcategory_id' => 3,
                'code' => 'GDH333-25',
                'name' => 'Tirador de puerta tipo S',
                'slug' => 'tirador-de-puerta-tipo-s',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            20 => 
            array (
                'id' => 21,
                'subcategory_id' => 3,
                'code' => 'GDH334-25',
                'name' => 'Tirador de puerta tipo O',
                'slug' => 'tirador-de-puerta-tipo-o',
                'description' => '30,5 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            21 => 
            array (
                'id' => 22,
                'subcategory_id' => 3,
                'code' => 'GDH341-50',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '30,5 cm de eje y 50 cm de largo',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            22 => 
            array (
                'id' => 23,
                'subcategory_id' => 3,
                'code' => 'GDH341-75',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '42,5 cm de eje y 75 cm de largo',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            23 => 
            array (
                'id' => 24,
                'subcategory_id' => 3,
                'code' => 'GDH341-90',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '50 cm de eje y 90 cm de largo',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            24 => 
            array (
                'id' => 25,
                'subcategory_id' => 3,
                'code' => 'GDH341A-75',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '42,5 cm de eje y 75 cm de largo',
                'finishing' => 4,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            25 => 
            array (
                'id' => 26,
                'subcategory_id' => 3,
                'code' => 'GDH341-CS150',
                'name' => 'Tirador de puerta tipo H con cerradura',
                'slug' => 'tirador-de-puerta-tipo-h-con-cerradura',
                'description' => '150 cm de largo',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            26 => 
            array (
                'id' => 27,
                'subcategory_id' => 3,
                'code' => 'GDH342-50D',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '30,5 cm de eje y 50 cm de largo',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            27 => 
            array (
                'id' => 28,
                'subcategory_id' => 3,
                'code' => 'GDH342-75D',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '42,5 cm de eje y 75 cm de largo',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            28 => 
            array (
                'id' => 29,
                'subcategory_id' => 3,
                'code' => 'GDH342-90D',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '50 cm de eje y 90 cm de largo',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            29 => 
            array (
                'id' => 30,
                'subcategory_id' => 3,
                'code' => 'GDH345-32',
                'name' => 'Tirador de puerta tipo H cónico',
                'slug' => 'tirador-de-puerta-tipo-h-conico',
                'description' => '30,5 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            30 => 
            array (
                'id' => 31,
                'subcategory_id' => 3,
                'code' => 'GDH345-D',
                'name' => 'Tirador de puerta tipo H cónico',
                'slug' => 'tirador-de-puerta-tipo-h-conico',
                'description' => '30,5 cm de eje',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            31 => 
            array (
                'id' => 32,
                'subcategory_id' => 3,
                'code' => 'GDH348',
                'name' => 'Tirador de puerta tipo H barra plana',
                'slug' => 'tirador-de-puerta-tipo-h-barra-plana',
                'description' => '30,5 cm de eje',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            32 => 
            array (
                'id' => 33,
                'subcategory_id' => 7,
                'code' => 'GDH731B',
                'name' => 'Conector grande pared-vidrio',
                'slug' => 'conector-grande-pared-vidrio',
                'description' => 'Medidas 5x5 cm',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            33 => 
            array (
                'id' => 34,
                'subcategory_id' => 7,
                'code' => 'GDH732A',
                'name' => 'Conector grande vidrio-vidrio 90˚',
                'slug' => 'conector-grande-vidrio-vidrio-90',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            34 => 
            array (
                'id' => 35,
                'subcategory_id' => 7,
                'code' => 'GDH734A',
                'name' => 'Conector grande vidrio-vidrio 180˚',
                'slug' => 'conector-grande-vidrio-vidrio-180',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            35 => 
            array (
                'id' => 36,
                'subcategory_id' => 7,
                'code' => 'GDH736A',
                'name' => 'Conector grande vidrio-vidrio 135˚',
                'slug' => 'conector-grande-vidrio-vidrio-135',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            36 => 
            array (
                'id' => 37,
                'subcategory_id' => 4,
                'code' => 'GDH580',
                'name' => 'Cerradura vidrio-vidrio sobrepuesta redonda',
                'slug' => 'cerradura-vidrio-vidrio-sobrepuesta-redonda',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            37 => 
            array (
                'id' => 38,
                'subcategory_id' => 4,
                'code' => 'GDH580A',
                'name' => 'Cerradura pared vidrio sobrepuesta redonda',
                'slug' => 'cerradura-pared-vidrio-sobrepuesta-redonda',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            38 => 
            array (
                'id' => 39,
                'subcategory_id' => 4,
                'code' => 'GDH592A',
                'name' => 'Cerradura Oasis con manilla vidrio-pared',
                'slug' => 'cerradura-oasis-con-manilla-vidrio-pared',
                'description' => 'Llave por ambos lados',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            39 => 
            array (
                'id' => 40,
                'subcategory_id' => 4,
                'code' => 'GDH592AC',
                'name' => 'Cerradura Oasis con manilla vidrio-vidrio',
                'slug' => 'cerradura-oasis-con-manilla-vidrio-vidrio',
                'description' => 'Doble manilla. Llave por ambos lados',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            40 => 
            array (
                'id' => 41,
                'subcategory_id' => 4,
                'code' => 'GDH592AB',
                'name' => 'Cerradura Oasis con manilla vidrio-vidrio',
                'slug' => 'cerradura-oasis-con-manilla-vidrio-vidrio',
                'description' => 'Llave por ambos lados',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            41 => 
            array (
                'id' => 42,
                'subcategory_id' => 4,
                'code' => 'GDH594A',
                'name' => 'Cerradura Isa pared-vidrio con manilla',
                'slug' => 'cerradura-isa-pared-vidrio-con-manilla',
                'description' => 'Llave por un lado y pasador por el otro',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            42 => 
            array (
                'id' => 43,
                'subcategory_id' => 4,
                'code' => 'GDH594AB',
                'name' => 'Cerradura Isa vidrio-vidrio',
                'slug' => 'cerradura-isa-vidrio-vidrio',
                'description' => 'Doble manilla. Llave por un lado y pasador por el otro',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            43 => 
            array (
                'id' => 44,
                'subcategory_id' => 4,
                'code' => 'GDH592V-Z',
                'name' => 'Cerradura Venus con manilla vidrio-vidrio',
                'slug' => 'cerradura-venus-con-manilla-vidrio-vidrio',
                'description' => 'Llave por un lado y pasador por el otro',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            44 => 
            array (
                'id' => 45,
                'subcategory_id' => 4,
                'code' => 'GDH8120',
                'name' => 'Cerradura rectagular grande con haladera vidrio-pared para embutir',
                'slug' => 'cerradura-rectagular-grande-con-haladera-vidrio-pared-para-embutir',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            45 => 
            array (
                'id' => 46,
                'subcategory_id' => 4,
                'code' => 'GDH8120-1',
                'name' => 'Cerradura rectagular grande con haladera vidrio-vidrio para embutir',
                'slug' => 'cerradura-rectagular-grande-con-haladera-vidrio-vidrio-para-embutir',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            46 => 
            array (
                'id' => 47,
                'subcategory_id' => 4,
                'code' => 'GDH824S',
                'name' => 'Cerradura circular embutida para solape de puerta corredera',
                'slug' => 'cerradura-circular-embutida-para-solape-de-puerta-corredera',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            47 => 
            array (
                'id' => 48,
                'subcategory_id' => 4,
                'code' => 'GDH590A',
                'name' => 'Cerradura redonda para Europivot',
                'slug' => 'cerradura-redonda-para-europivot',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            48 => 
            array (
                'id' => 49,
                'subcategory_id' => 4,
                'code' => 'GDH590Z',
                'name' => 'Cerradura cuadrada para Europivot',
                'slug' => 'cerradura-cuadrada-para-europivot',
                'description' => '8,5 x 9,7 cm',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            49 => 
            array (
                'id' => 50,
                'subcategory_id' => 4,
                'code' => 'GDH597S',
                'name' => 'Cerradura pared-vidrio cuadrada sobrepuesta con llave por un solo lado',
                'slug' => 'cerradura-pared-vidrio-cuadrada-sobrepuesta-con-llave-por-un-solo-lado',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            50 => 
            array (
                'id' => 51,
                'subcategory_id' => 5,
                'code' => '7125',
                'name' => 'Freno hidráulico de piso MAB',
                'slug' => 'freno-hidraulico-de-piso-mab',
                'description' => 'Capacidad máxima 100 Kg',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:50',
            ),
            51 => 
            array (
                'id' => 52,
                'subcategory_id' => 5,
                'code' => 'M25',
                'name' => 'Freno hidráulico de piso Speedy',
                'slug' => 'freno-hidraulico-de-piso-speedy',
                'description' => 'Capacidad máxima 120 Kg',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            52 => 
            array (
                'id' => 53,
                'subcategory_id' => 6,
                'code' => 'GDH112A',
                'name' => 'Pivote loco',
                'slug' => 'pivote-loco',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            53 => 
            array (
                'id' => 54,
                'subcategory_id' => 6,
                'code' => 'GDH050-5',
                'name' => 'Recibidor al piso',
                'slug' => 'recibidor-al-piso',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            54 => 
            array (
                'id' => 55,
                'subcategory_id' => 6,
                'code' => 'GDH112B',
                'name' => 'Pivote superior fijo',
                'slug' => 'pivote-superior-fijo',
                'description' => 'Pin 15mm',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            55 => 
            array (
                'id' => 56,
                'subcategory_id' => 6,
                'code' => 'GDH771',
                'name' => 'Tope de piso',
                'slug' => 'tope-de-piso',
                'description' => 'Fabricado en acero inoxidable. Protector de goma.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            56 => 
            array (
                'id' => 57,
                'subcategory_id' => 7,
                'code' => 'GDH741',
                'name' => 'Conector pared-vidrio 90° tipo boton',
                'slug' => 'conector-pared-vidrio-90-tipo-boton',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            57 => 
            array (
                'id' => 58,
                'subcategory_id' => 7,
                'code' => 'GDH742',
                'name' => 'Conector vidrio-vidrio 90° tipo boton',
                'slug' => 'conector-vidrio-vidrio-90-tipo-boton',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            58 => 
            array (
                'id' => 59,
                'subcategory_id' => 7,
                'code' => 'GDH744',
                'name' => 'Conector vidrio-vidrio 180° tipo boton',
                'slug' => 'conector-vidrio-vidrio-180-tipo-boton',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            59 => 
            array (
                'id' => 60,
                'subcategory_id' => 7,
                'code' => 'GDH745',
                'name' => 'Conector pared-vidrio 180° tipo boton',
                'slug' => 'conector-pared-vidrio-180-tipo-boton',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            60 => 
            array (
                'id' => 61,
                'subcategory_id' => 8,
                'code' => 'GDH512',
                'name' => 'Bisagra grande pared-vidrio',
                'slug' => 'bisagra-grande-pared-vidrio',
                'description' => 'Medidas 9x5,5 cm',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            61 => 
            array (
                'id' => 62,
                'subcategory_id' => 8,
                'code' => 'GDH513',
                'name' => 'Bisagra grande desplazada pared-vidrio',
                'slug' => 'bisagra-grande-desplazada-pared-vidrio',
                'description' => 'Medidas 9x5,5 cm',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            62 => 
            array (
                'id' => 63,
                'subcategory_id' => 8,
                'code' => 'GDH514',
                'name' => 'Bisagra grande vidrio-vidrio 90˚',
                'slug' => 'bisagra-grande-vidrio-vidrio-90',
                'description' => 'Medidas 9x5,5 cm',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            63 => 
            array (
                'id' => 64,
                'subcategory_id' => 8,
                'code' => 'GDH516',
                'name' => 'Bisagra grande vidrio-vidrio 135˚',
                'slug' => 'bisagra-grande-vidrio-vidrio-135',
                'description' => 'Medidas 9x5,5 cm',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            64 => 
            array (
                'id' => 65,
                'subcategory_id' => 8,
                'code' => 'GDH518',
                'name' => 'Bisagra grande vidrio-vidrio 180˚',
                'slug' => 'bisagra-grande-vidrio-vidrio-180',
                'description' => 'Medidas 9x5,5 cm',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            65 => 
            array (
                'id' => 66,
                'subcategory_id' => 9,
                'code' => 'GDH336-45',
                'name' => 'Toallero para puerta de baño',
                'slug' => 'toallero-para-puerta-de-bano',
                'description' => '45 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            66 => 
            array (
                'id' => 67,
                'subcategory_id' => 9,
                'code' => 'GDH336-55',
                'name' => 'Toallero para puerta de baño',
                'slug' => 'toallero-para-puerta-de-bano',
                'description' => '55 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            67 => 
            array (
                'id' => 68,
                'subcategory_id' => 9,
                'code' => 'GDH337-19',
                'name' => 'Tirador para puerta de baño tipo L',
                'slug' => 'tirador-para-puerta-de-bano-tipo-l',
                'description' => '15 x 45 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            68 => 
            array (
                'id' => 69,
                'subcategory_id' => 9,
                'code' => 'GDH338-19',
                'name' => 'Tirador para puerta de baño tipo L',
                'slug' => 'tirador-para-puerta-de-bano-tipo-l',
                'description' => '20 x 55 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            69 => 
            array (
                'id' => 70,
                'subcategory_id' => 9,
                'code' => 'GDH334-15',
                'name' => 'Tirador para puerta de baño tipo C',
                'slug' => 'tirador-para-puerta-de-bano-tipo-c',
                'description' => '15 cm de eje',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            70 => 
            array (
                'id' => 71,
                'subcategory_id' => 9,
                'code' => 'GDH341-22',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '15 cm de eje y 22 de largo',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            71 => 
            array (
                'id' => 72,
                'subcategory_id' => 9,
                'code' => 'GDH341-22D',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '15 cm de eje y 22 de largo',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            72 => 
            array (
                'id' => 73,
                'subcategory_id' => 9,
                'code' => 'GDH342-22',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => 'Punteado en el centro. 15 cm de eje y 22 de largo.',
                'finishing' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            73 => 
            array (
                'id' => 74,
                'subcategory_id' => 10,
                'code' => 'GDH221',
                'name' => 'Pomo de puerta esférico',
                'slug' => 'pomo-de-puerta-esferico',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            74 => 
            array (
                'id' => 75,
                'subcategory_id' => 10,
                'code' => 'GDH222',
                'name' => 'Pomo de puerta cónico',
                'slug' => 'pomo-de-puerta-conico',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            75 => 
            array (
                'id' => 76,
                'subcategory_id' => 10,
                'code' => 'GDH222A',
                'name' => 'Pomo de puerta cónico acanalado',
                'slug' => 'pomo-de-puerta-conico-acanalado',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            76 => 
            array (
                'id' => 77,
                'subcategory_id' => 10,
                'code' => 'GDH223',
                'name' => 'Pomo de puerta cilíndrico estriado',
                'slug' => 'pomo-de-puerta-cilindrico-estriado',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            77 => 
            array (
                'id' => 79,
                'subcategory_id' => 10,
                'code' => 'GDH225',
                'name' => 'Pomo de puerta tipo huella cilíndrico doble',
                'slug' => 'pomo-de-puerta-tipo-huella-cilindrico-doble',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            78 => 
            array (
                'id' => 80,
                'subcategory_id' => 10,
                'code' => 'GDH225 Half',
                'name' => 'Pomo de puerta cilíndrico tipo huella sencillo grande',
                'slug' => 'pomo-de-puerta-cilindrico-tipo-huella-sencillo-grande',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            79 => 
            array (
                'id' => 81,
                'subcategory_id' => 10,
                'code' => 'GDH225-1',
                'name' => 'Pomo de puerta cilindrico sencillo pequeño',
                'slug' => 'pomo-de-puerta-cilindrico-sencillo-pequeno',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            80 => 
            array (
                'id' => 84,
                'subcategory_id' => 10,
                'code' => 'GDH227',
                'name' => 'Pomo de puerta cilindrico acanalado',
                'slug' => 'pomo-de-puerta-cilindrico-acanalado',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            81 => 
            array (
                'id' => 86,
                'subcategory_id' => 11,
                'code' => 'GDH791',
                'name' => 'Brazo tensor extendible',
                'slug' => 'brazo-tensor-extendible',
                'description' => '70 a 90 cm. Terminación 90˚.',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            82 => 
            array (
                'id' => 87,
                'subcategory_id' => 11,
                'code' => 'GDH791A',
                'name' => 'Brazo tensor extendible',
                'slug' => 'brazo-tensor-extendible',
                'description' => '30 a 50 cm. Terminación 45˚.',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            83 => 
            array (
                'id' => 88,
                'subcategory_id' => 12,
                'code' => 'GDH202-8',
                'name' => 'Policarbonato hongo para vidrio',
                'slug' => 'policarbonato-hongo-para-vidrio',
                'description' => 'Para vidrio de 8mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            84 => 
            array (
                'id' => 89,
                'subcategory_id' => 12,
                'code' => 'GDH202-10',
                'name' => 'Policarbonato hongo para vidrio',
                'slug' => 'policarbonato-hongo-para-vidrio',
                'description' => 'Para vidrio de 10mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            85 => 
            array (
                'id' => 90,
                'subcategory_id' => 12,
                'code' => 'GDH206',
                'name' => 'Policarbonato ala lateral',
                'slug' => 'policarbonato-ala-lateral',
                'description' => 'Para vidrio de 8mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            86 => 
            array (
                'id' => 91,
                'subcategory_id' => 12,
                'code' => 'GDH206-10',
                'name' => 'Policarbonato ala lateral para vidrio',
                'slug' => 'policarbonato-ala-lateral-para-vidrio',
                'description' => 'Para vidrio de 10mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            87 => 
            array (
                'id' => 92,
                'subcategory_id' => 12,
                'code' => 'GDH206-8R',
                'name' => 'Policarbonato ala lateral rígida',
                'slug' => 'policarbonato-ala-lateral-rigida',
                'description' => 'Para vidrio de 8mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            88 => 
            array (
                'id' => 93,
                'subcategory_id' => 12,
                'code' => 'GDH207-8',
                'name' => 'Policarbonato ala central',
                'slug' => 'policarbonato-ala-central',
                'description' => 'Para vidrio de 8mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            89 => 
            array (
                'id' => 94,
                'subcategory_id' => 12,
                'code' => 'GDH208',
                'name' => 'Policarbonato doble ala central',
                'slug' => 'policarbonato-doble-ala-central',
                'description' => 'Para vidrio de 8mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            90 => 
            array (
                'id' => 95,
                'subcategory_id' => 12,
                'code' => 'GDH211',
                'name' => 'Policarbonato con imán',
                'slug' => 'policarbonato-con-iman',
                'description' => 'Para vidrio de 8mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            91 => 
            array (
                'id' => 96,
                'subcategory_id' => 13,
                'code' => 'GDH205-25M',
                'name' => 'Distanciador',
                'slug' => 'distanciador',
                'description' => 'Macizo. Acero Inoxidable. Medidas 2,5 cm x 25 mm.',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            92 => 
            array (
                'id' => 97,
                'subcategory_id' => 13,
                'code' => 'GDH205-40M',
                'name' => 'Distanciador',
                'slug' => 'distanciador',
                'description' => 'Macizo. Acero Inoxidable. Medidas 4 cm x 25 mm.',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            93 => 
            array (
                'id' => 98,
                'subcategory_id' => 13,
                'code' => 'GDH205-32-60M',
                'name' => 'Distanciador',
                'slug' => 'distanciador',
                'description' => 'Macizo. Acero Inoxidable. Medidas 6 cm x 32 mm.',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            94 => 
            array (
                'id' => 99,
                'subcategory_id' => 13,
                'code' => 'GDH205-40-40M',
                'name' => 'Distanciador',
                'slug' => 'distanciador',
                'description' => 'Macizo. Acero Inoxidable. Medidas 4 cm x 40 mm.',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            95 => 
            array (
                'id' => 100,
                'subcategory_id' => 13,
                'code' => 'GDH205-40-70M',
                'name' => 'Distanciador',
                'slug' => 'distanciador',
                'description' => 'Macizo. Acero Inoxidable. Medidas 7 cm x 40 mm.',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            96 => 
            array (
                'id' => 101,
                'subcategory_id' => 13,
                'code' => 'GDH671C',
                'name' => 'Soporte pared-vidrio cabeza plana',
                'slug' => 'soporte-pared-vidrio-cabeza-plana',
                'description' => 'Fabricado en acero inoxidable ',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            97 => 
            array (
                'id' => 102,
                'subcategory_id' => 25,
                'code' => 'GDH763',
                'name' => 'Soporte baranda cuadrado base curva',
                'slug' => 'soporte-baranda-cuadrado-base-curva',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            98 => 
            array (
                'id' => 103,
                'subcategory_id' => 25,
                'code' => 'GDH763A',
                'name' => 'Soporte baranda cuadrado base plana',
                'slug' => 'soporte-baranda-cuadrado-base-plana',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            99 => 
            array (
                'id' => 104,
                'subcategory_id' => 14,
                'code' => 'GDH672',
                'name' => 'Araña doble pequeña',
                'slug' => 'arana-doble-pequena',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            100 => 
            array (
                'id' => 105,
                'subcategory_id' => 14,
                'code' => 'GDH672B',
                'name' => 'Araña sencilla pequeña',
                'slug' => 'arana-sencilla-pequena',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            101 => 
            array (
                'id' => 106,
                'subcategory_id' => 14,
                'code' => 'GDH-A100',
                'name' => 'Rótula articulada plana',
                'slug' => 'rotula-articulada-plana',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            102 => 
            array (
                'id' => 107,
                'subcategory_id' => 14,
                'code' => 'GDH-A101',
                'name' => 'Araña estructural de 1 vía',
                'slug' => 'arana-estructural-de-1-via',
                'description' => '200mm de distancia entre ejes',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            103 => 
            array (
                'id' => 108,
                'subcategory_id' => 14,
                'code' => 'GDH-A102',
                'name' => 'Araña estructural de 2 vías',
                'slug' => 'arana-estructural-de-2-vias',
                'description' => '200mm de distancia entre ejes',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:51',
            ),
            104 => 
            array (
                'id' => 109,
                'subcategory_id' => 14,
                'code' => 'GDH-A103',
                'name' => 'Araña estructural de 3 vías',
                'slug' => 'arana-estructural-de-3-vias',
                'description' => '200mm de distancia entre ejes',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            105 => 
            array (
                'id' => 110,
                'subcategory_id' => 14,
                'code' => 'GDH-A104',
                'name' => 'Araña estructural de 4 vías',
                'slug' => 'arana-estructural-de-4-vias',
                'description' => '200mm de distancia entre ejes',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            106 => 
            array (
                'id' => 111,
                'subcategory_id' => 15,
                'code' => 'GDH751',
            'name' => 'Repisero semicircular para vidrio de 8mm (par)',
                'slug' => 'repisero-semicircular-para-vidrio-de-8mm-par',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            107 => 
            array (
                'id' => 112,
                'subcategory_id' => 15,
                'code' => 'GDH752',
            'name' => 'Repisero semicircular para vidrio de 10mm (par)',
                'slug' => 'repisero-semicircular-para-vidrio-de-10mm-par',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            108 => 
            array (
                'id' => 113,
                'subcategory_id' => 15,
                'code' => 'GDH753',
            'name' => 'Repisero semicircular para vidrio de 12mm (par)',
                'slug' => 'repisero-semicircular-para-vidrio-de-12mm-par',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            109 => 
            array (
                'id' => 114,
                'subcategory_id' => 15,
                'code' => 'GDH902',
            'name' => 'Repisero tipo Tucán (par)',
                'slug' => 'repisero-tipo-tucan-par',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            110 => 
            array (
                'id' => 115,
                'subcategory_id' => 15,
                'code' => 'GDH903',
            'name' => 'Repisero tipo Tucán cuadrado (par)',
                'slug' => 'repisero-tipo-tucan-cuadrado-par',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            111 => 
            array (
                'id' => 116,
                'subcategory_id' => 15,
                'code' => 'GDH312',
                'name' => 'Bisagra empotrable pequeña para vitrina',
                'slug' => 'bisagra-empotrable-pequena-para-vitrina',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            112 => 
            array (
                'id' => 117,
                'subcategory_id' => 16,
                'code' => 'Felpa 48N',
                'name' => 'Felpa Negra 4.8 mm',
                'slug' => 'felpa-negra-48-mm',
                'description' => 'Rollo de 400 m. Ecobell. Project.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            113 => 
            array (
                'id' => 118,
                'subcategory_id' => 16,
                'code' => 'Felpa 57N',
                'name' => 'Felpa Negra 5.7 mm',
                'slug' => 'felpa-negra-57-mm',
                'description' => 'Rollo de 400 m. Panorámica.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            114 => 
            array (
                'id' => 119,
                'subcategory_id' => 16,
                'code' => 'Felpa 69N',
                'name' => 'Felpa Negra 6.9 mm',
                'slug' => 'felpa-negra-69-mm',
                'description' => 'Rollo de 400 m. Caroní.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            115 => 
            array (
                'id' => 120,
                'subcategory_id' => 17,
                'code' => 'GDH206A3',
            'name' => 'Policarbonato ala lateral panorámico transparente (guardapolvo)',
                'slug' => 'policarbonato-ala-lateral-panoramico-transparente-guardapolvo',
                'description' => 'Para vidrio de 8mm. Barra de 3mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            116 => 
            array (
                'id' => 121,
                'subcategory_id' => 17,
                'code' => 'GDH206A3N',
            'name' => 'Policarbonato ala lateral panorámico negro (guardapolvo)',
                'slug' => 'policarbonato-ala-lateral-panoramico-negro-guardapolvo',
                'description' => 'Para vidrio de 8mm. Barra de 3mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            117 => 
            array (
                'id' => 122,
                'subcategory_id' => 19,
                'code' => 'GDH H602',
                'name' => 'Ventosa doble',
                'slug' => 'ventosa-doble',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            118 => 
            array (
                'id' => 123,
                'subcategory_id' => 19,
                'code' => 'GDH H603',
                'name' => 'Ventosa triple',
                'slug' => 'ventosa-triple',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            119 => 
            array (
                'id' => 124,
                'subcategory_id' => 18,
                'code' => 'GDH-V101',
                'name' => 'Rodamiento sencillo ventana Caroní',
                'slug' => 'rodamiento-sencillo-ventana-caroni',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            120 => 
            array (
                'id' => 125,
                'subcategory_id' => 18,
                'code' => 'GDH-V102',
                'name' => 'Rodamiento doble ventana Caroní',
                'slug' => 'rodamiento-doble-ventana-caroni',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            121 => 
            array (
                'id' => 126,
                'subcategory_id' => 18,
                'code' => 'GDH-V103',
                'name' => 'Kit plástico ventana Caroní',
                'slug' => 'kit-plastico-ventana-caroni',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            122 => 
            array (
                'id' => 127,
                'subcategory_id' => 18,
                'code' => 'GDH-V104',
                'name' => 'Escuadra ventana Caroní',
                'slug' => 'escuadra-ventana-caroni',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            123 => 
            array (
                'id' => 128,
                'subcategory_id' => 18,
                'code' => 'GDH-V201',
                'name' => 'Rueda para Ventana Panorámica',
                'slug' => 'rueda-para-ventana-panoramica',
                'description' => 'Incluye sus respectivas tapas',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            124 => 
            array (
                'id' => 129,
                'subcategory_id' => 18,
                'code' => 'GDH-V202',
                'name' => 'Trancador de pin para Ventana Panorámica',
                'slug' => 'trancador-de-pin-para-ventana-panoramica',
                'description' => '',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            125 => 
            array (
                'id' => 130,
                'subcategory_id' => 18,
                'code' => 'GDH-V203',
                'name' => 'Trancador con llave para Ventana',
                'slug' => 'trancador-con-llave-para-ventana',
                'description' => 'Color negro',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            126 => 
            array (
                'id' => 131,
                'subcategory_id' => 18,
                'code' => 'GDH-V302',
                'name' => 'Trancador de tic tac para Ventana',
                'slug' => 'trancador-de-tic-tac-para-ventana',
                'description' => 'Color negro',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            127 => 
            array (
                'id' => 132,
                'subcategory_id' => 18,
                'code' => 'GDH-V536A',
                'name' => 'Manilla para ventana proyectante',
                'slug' => 'manilla-para-ventana-proyectante',
                'description' => 'Color negro',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            128 => 
            array (
                'id' => 133,
                'subcategory_id' => 20,
                'code' => 'GDH-S7500',
                'name' => 'Kit de Puerta Euroslider',
                'slug' => 'kit-de-puerta-euroslider',
                'description' => 'Sistema de puerta colgante con tubo redondo de acero
inoxidable de 25mm y rodamiento tipo Eurocolgante.<br><span>Se vende el kit de acuerdo a la configuración requerida</span>',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            129 => 
            array (
                'id' => 134,
                'subcategory_id' => 22,
                'code' => 'GDH-S7600',
                'name' => 'Kit de Puerta Corrediza de 19mm',
                'slug' => 'kit-de-puerta-corrediza-de-19mm',
                'description' => 'Sistema de puerta corredera de acero inoxidable con tubo redondo de 19mm y rueda tipo botón.<br>
80kg de peso máximo por puerta.<br><span>Se vende el kit de acuerdo a la configuración requerida</span>',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            130 => 
            array (
                'id' => 135,
                'subcategory_id' => 22,
                'code' => 'GDH-S7800',
                'name' => 'Kit para Puerta Corrediza de tubo rectangular',
                'slug' => 'kit-para-puerta-corrediza-de-tubo-rectangular',
                'description' => 'Sistema de puerta corredera de acero inoxidable con tubo rectangular y rodamiento tipo botón.<br>
80kg de peso máximo por puerta.<br>
Incluye: 2 soportes tubo-pared, 2 rodamientos, 2 antidescarrilantes, 2 topes, 2 conectores tubo-vidrio, 1 guía de piso, 1 tirador embutido y 1
tubo rectangular (2 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            131 => 
            array (
                'id' => 136,
                'subcategory_id' => 21,
                'code' => 'GDH-S5100',
                'name' => 'Kit para Puerta Colgante modelo Araña',
                'slug' => 'kit-para-puerta-colgante-modelo-arana',
                'description' => 'Sistema de puerta colgante todo visión con rueda modelo araña y riel de aluminio de 2 metros.
100kg de peso máximo por puerta.<br>
Incluye: 2 rodamientos, 2 topes, 1 guía de piso y 1 riel de aluminio (2 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            132 => 
            array (
                'id' => 137,
                'subcategory_id' => 21,
                'code' => 'GDH-S6100',
                'name' => 'Kit para Puerta Colgante modelo
Alfa',
                'slug' => 'kit-para-puerta-colgante-modeloalfa',
                'description' => 'Sistema de puerta colgante todo visión con rueda modelo alfa y riel de aluminio de 2mts. 100kg de peso máximo por puerta.<br>
Incluye: 2 rodamientos, 2 topes, 1 guía de piso, 1 llave y 1 riel de aluminio (2 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            133 => 
            array (
                'id' => 138,
                'subcategory_id' => 21,
                'code' => 'GDH-S7100-2',
                'name' => 'Kit para Puerta Colgante con Cenefa',
                'slug' => 'kit-para-puerta-colgante-con-cenefa',
            'description' => 'Sistema de puerta colgante todo visión con riel fijo y tapas de aluminio. 120kg de peso máximo por puerta.<br>Incluye: 2 rodamientos, 2 topes, 1 guía de piso, 1 llave, 1 riel, 1 fijo y dos tapas de aluminio (2 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            134 => 
            array (
                'id' => 139,
                'subcategory_id' => 23,
                'code' => 'GDH-S800',
                'name' => 'Sistema Puerta Plegable',
                'slug' => 'sistema-puerta-plegable',
                'description' => 'Sistema de puerta plegable para vidrio de 10mm. Carga máxima por hoja de 60kg.<br><span>Se vende el kit de acuerdo a la configuración requerida</span>',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            135 => 
            array (
                'id' => 140,
                'subcategory_id' => 25,
                'code' => 'GDH762',
                'name' => 'Soporte baranda base curva',
                'slug' => 'soporte-baranda-base-curva',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            136 => 
            array (
                'id' => 141,
                'subcategory_id' => 24,
                'code' => 'GDH-D6108',
                'name' => 'Sistema Puerta Automática',
                'slug' => 'sistema-puerta-automatica',
                'description' => 'Automatismo para puerta caracterizado por su robustez y confiabilidad. Riel de aluminio de alta resistencia. Microordenador de control inteligente. Longitud de 4,20mts. Tapa de acero inoxidable quita y pon. Mecanismo para 1 o 2 hojas. De fácil instalación. Para uso en lugares de alto tráfico.<br>
Carga máxima por hoja de 120kg.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            137 => 
            array (
                'id' => 142,
                'subcategory_id' => 1,
                'code' => 'GDH055B',
                'name' => 'Recibidor para cerradura central de puerta Todo Visión vidrio-vidrio',
                'slug' => 'recibidor-para-cerradura-central-de-puerta-todo-vision-vidrio-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            138 => 
            array (
                'id' => 143,
                'subcategory_id' => 14,
                'code' => 'GDH675A',
                'name' => 'Conector sencillo articulado
vidrio-pared',
                'slug' => 'conector-sencillo-articuladovidrio-pared',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            139 => 
            array (
                'id' => 144,
                'subcategory_id' => 14,
                'code' => 'GDH675C',
                'name' => 'Conector triple articulado
vidrio-vidrio',
                'slug' => 'conector-triple-articuladovidrio-vidrio',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            140 => 
            array (
                'id' => 145,
                'subcategory_id' => 14,
                'code' => 'GDH675B',
                'name' => 'Conector doble articulado
vidrio-vidrio',
                'slug' => 'conector-doble-articuladovidrio-vidrio',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            141 => 
            array (
                'id' => 146,
                'subcategory_id' => 14,
                'code' => 'GDH-A201',
                'name' => 'Araña estructural con cartela de 1 vía',
                'slug' => 'arana-estructural-con-cartela-de-1-via',
                'description' => '200mm de distancia entre ejes',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            142 => 
            array (
                'id' => 147,
                'subcategory_id' => 14,
                'code' => 'GDH-A202',
                'name' => 'Araña estructural con cartela de 2 vías',
                'slug' => 'arana-estructural-con-cartela-de-2-vias',
                'description' => '200mm de distancia entre ejes',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            143 => 
            array (
                'id' => 148,
                'subcategory_id' => 26,
                'code' => 'GDH-B010',
                'name' => 'Conector pasamano-vidrio',
                'slug' => 'conector-pasamano-vidrio',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            144 => 
            array (
                'id' => 149,
                'subcategory_id' => 26,
                'code' => 'GDH-B011',
                'name' => 'Conector pasamano-pared',
                'slug' => 'conector-pasamano-pared',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            145 => 
            array (
                'id' => 150,
                'subcategory_id' => 26,
                'code' => 'GDH-B012',
                'name' => 'Pie de baranda rígido',
                'slug' => 'pie-de-baranda-rigido',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            146 => 
            array (
                'id' => 151,
                'subcategory_id' => 26,
                'code' => 'GDH-B013',
                'name' => 'Conector pasamano articulado para tubo de 1 ½”',
                'slug' => 'conector-pasamano-articulado-para-tubo-de-1-1/2',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            147 => 
            array (
                'id' => 152,
                'subcategory_id' => 25,
                'code' => 'GDH-B018',
                'name' => 'Soporte de baranda base curva',
                'slug' => 'soporte-de-baranda-base-curva',
                'description' => 'Material: Acero inoxidable',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            148 => 
            array (
                'id' => 153,
                'subcategory_id' => 26,
                'code' => 'GDH-B201',
                'name' => 'Tapa plana para tubo de 2”',
                'slug' => 'tapa-plana-para-tubo-de-2',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            149 => 
            array (
                'id' => 154,
                'subcategory_id' => 26,
                'code' => 'GDH-B220',
                'name' => 'Codo de 90 grados para tubo de 2”',
                'slug' => 'codo-de-90-grados-para-tubo-de-2',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            150 => 
            array (
                'id' => 155,
                'subcategory_id' => 26,
                'code' => 'GDH-B221',
                'name' => 'Codo de 135 grados para tubo de 2”',
                'slug' => 'codo-de-135-grados-para-tubo-de-2',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            151 => 
            array (
                'id' => 156,
                'subcategory_id' => 26,
                'code' => 'GDH-B225',
                'name' => 'Unión para tubo de 2”',
                'slug' => 'union-para-tubo-de-2',
                'description' => '',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            152 => 
            array (
                'id' => 157,
                'subcategory_id' => 5,
                'code' => 'P502',
                'name' => 'Brazo hidráulico para puerta enmarcada',
                'slug' => 'brazo-hidraulico-para-puerta-enmarcada',
                'description' => 'Capacidad máxima 60 Kg',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            153 => 
            array (
                'id' => 158,
                'subcategory_id' => 5,
                'code' => 'P503',
                'name' => 'Brazo hidráulico para puerta enmarcada',
                'slug' => 'brazo-hidraulico-para-puerta-enmarcada',
                'description' => 'Capacidad máxima 45 Kg',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            154 => 
            array (
                'id' => 159,
                'subcategory_id' => 8,
                'code' => 'GDH712',
                'name' => 'Bisagra pivotante pared-vidrio',
                'slug' => 'bisagra-pivotante-pared-vidrio',
                'description' => '',
                'finishing' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            155 => 
            array (
                'id' => 160,
                'subcategory_id' => 25,
                'code' => 'GDH762A',
                'name' => 'Soporte baranda base plana',
                'slug' => 'soporte-baranda-base-plana',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            156 => 
            array (
                'id' => 161,
                'subcategory_id' => 1,
                'code' => 'GDH055',
                'name' => 'Cerradura para puerta Todo Vision',
                'slug' => 'cerradura-para-puerta-todo-vision',
                'description' => 'Con Pin',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:52',
            ),
            157 => 
            array (
                'id' => 162,
                'subcategory_id' => 27,
                'code' => 'GDH B001',
                'name' => 'Tubo de acero inoxidable 304 de 2”',
                'slug' => 'tubo-de-acero-inoxidable-304-de-2',
                'description' => 'Diámetro 50,8mm',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            158 => 
            array (
                'id' => 163,
                'subcategory_id' => 19,
                'code' => 'GDH H600 ',
                'name' => 'Herramienta doble pin para Europivot',
                'slug' => 'herramienta-doble-pin-para-europivot',
                'description' => 'Protector de goma',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            159 => 
            array (
                'id' => 164,
                'subcategory_id' => 21,
                'code' => 'GDH-S7100-4',
                'name' => 'Kit para Puerta Colgante con Cenefa',
                'slug' => 'kit-para-puerta-colgante-con-cenefa',
                'description' => 'Sistema de puerta colgante todo visión con riel fijo y tapas de aluminio. 120kg de peso máximo por puerta.<br>Incluye: 4 rodamientos, 4 topes, 2 guía de piso, 1 llave, 1 riel, 1 fijo y dos tapas de
aluminio (4 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            160 => 
            array (
                'id' => 165,
                'subcategory_id' => 22,
                'code' => 'GDH-S7400',
                'name' => 'Kit para Puerta Corrediza de tubo cuadrado',
                'slug' => 'kit-para-puerta-corrediza-de-tubo-cuadrado',
                'description' => 'Sistema de puerta corredera de acero inoxidable con tubo cuadrado y rodamiento rectangular.<br>
80kg de peso máximo por puerta.<br>
Incluye: 2 soportes tubo-pared, 2 rodamientos, 2 topes, 2 conectores tubo-vidrio, 1 guía de piso, 1 tirador embutido
y 1 tubo cuadrado (2 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            161 => 
            array (
                'id' => 166,
                'subcategory_id' => 4,
                'code' => 'GDH503A',
                'name' => 'Cerradura pequeña con pin pared-vidrio',
                'slug' => 'cerradura-pequena-con-pin-pared-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            162 => 
            array (
                'id' => 167,
                'subcategory_id' => 4,
                'code' => 'GDH503AB',
                'name' => 'Cerradura pequeña con pin vidrio-vidrio',
                'slug' => 'cerradura-pequena-con-pin-vidrio-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            163 => 
            array (
                'id' => 168,
                'subcategory_id' => 4,
                'code' => 'GDH504A',
                'name' => 'Cerradura pequeña sobrepuesta ovalada con pin pared-vidrio',
                'slug' => 'cerradura-pequena-sobrepuesta-ovalada-con-pin-pared-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            164 => 
            array (
                'id' => 169,
                'subcategory_id' => 4,
                'code' => 'GDH504AB',
                'name' => 'Cerradura pequeña sobrepuesta ovalada con pin vidrio-vidrio',
                'slug' => 'cerradura-pequena-sobrepuesta-ovalada-con-pin-vidrio-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            165 => 
            array (
                'id' => 170,
                'subcategory_id' => 4,
                'code' => 'GDH505A',
                'name' => 'Cerradura pequeña sobrepuesta ovalada con llave pared-vidrio',
                'slug' => 'cerradura-pequena-sobrepuesta-ovalada-con-llave-pared-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            166 => 
            array (
                'id' => 171,
                'subcategory_id' => 4,
                'code' => 'GDH505AB',
                'name' => 'Cerradura pequeña sobrepuesta ovalada con llave vidrio-vidrio',
                'slug' => 'cerradura-pequena-sobrepuesta-ovalada-con-llave-vidrio-vidrio',
                'description' => '',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            167 => 
            array (
                'id' => 172,
                'subcategory_id' => 27,
                'code' => 'GDH B002',
                'name' => 'Tubo de acero inoxidable 304 de 1 1/2”',
                'slug' => 'tubo-de-acero-inoxidable-304-de-1-1/2',
                'description' => 'Diámetro 38mm',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:36:16',
            ),
            168 => 
            array (
                'id' => 173,
                'subcategory_id' => 28,
                'code' => 'GDH-B300',
                'name' => 'Pie de baranda en acero inoxidable',
                'slug' => 'pie-de-baranda-en-acero-inoxidable',
                'description' => 'Cuerpo de tubo redondo 1 ½”',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            169 => 
            array (
                'id' => 174,
                'subcategory_id' => 28,
                'code' => 'GDH-B320',
                'name' => 'Pie de baranda en acero inoxidable',
                'slug' => 'pie-de-baranda-en-acero-inoxidable',
                'description' => 'Cuerpo de doble paltina',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            170 => 
            array (
                'id' => 175,
                'subcategory_id' => 28,
                'code' => 'GDH-B310',
                'name' => 'Pie de baranda en acero inoxidable',
                'slug' => 'pie-de-baranda-en-acero-inoxidable',
                'description' => 'Cuerpo de platina lateral y apoyo vertical',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            171 => 
            array (
                'id' => 176,
                'subcategory_id' => 28,
                'code' => 'GDH-B340',
                'name' => 'Pie de baranda en acero inoxidable',
                'slug' => 'pie-de-baranda-en-acero-inoxidable',
                'description' => 'Cuerpo de doble platina decorativa',
                'finishing' => 2,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            172 => 
            array (
                'id' => 177,
                'subcategory_id' => 21,
                'code' => 'GDH-S4100',
                'name' => 'Kit para Puerta Colgante Modelo Tubular',
                'slug' => 'kit-para-puerta-colgante-modelo-tubular',
                'description' => 'Sistema de puerta colgante todo visión con rueda tubular.<br>
Riel de aluminio de 2 metros.<br>
100kg de peso máximo por puerta.<br>
Incluye: 2 rodamientos, 2 topes, 1 guía de piso y 1 riel de aluminio (2 metros).',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            173 => 
            array (
                'id' => 178,
                'subcategory_id' => 2,
                'code' => 'GDH-D681',
                'name' => 'Tope de puerta superior pared-vidrio
tipo Europivots',
                'slug' => 'tope-de-puerta-superior-pared-vidriotipo-europivots',
                'description' => 'Protector de goma',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            174 => 
            array (
                'id' => 179,
                'subcategory_id' => 18,
                'code' => 'GDH-V303',
                'name' => 'Trancador tic tac con manilla para ventana
',
                'slug' => 'trancador-tic-tac-con-manilla-para-ventana',
                'description' => 'Color blanco o negro',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            175 => 
            array (
                'id' => 180,
                'subcategory_id' => 3,
                'code' => 'GDH341-120',
                'name' => 'Tirador de puerta tipo H',
                'slug' => 'tirador-de-puerta-tipo-h',
                'description' => '90 cm de eje y 120 cm de largo',
                'finishing' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            176 => 
            array (
                'id' => 181,
                'subcategory_id' => 6,
                'code' => 'GDH112B-1',
                'name' => 'Pivote superior fijo',
                'slug' => 'pivote-superior-fijo',
                'description' => 'Pin 12mm',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
            177 => 
            array (
                'id' => 183,
                'subcategory_id' => 12,
                'code' => 'GDH207-10',
                'name' => 'Policarbonato ala central',
                'slug' => 'policarbonato-ala-central',
                'description' => 'Para vidrio de 10mm. Barra de 2,20 mts.',
                'finishing' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-03-28 18:28:53',
            ),
        ));
        
        
    }
}